# Generated by Django 5.1.3 on 2024-11-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='ExportReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('export_date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_receipts', to='accounts.employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_receipts', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'export_receipt',
            },
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('import_date', models.DateTimeField()),
                ('total_amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_receipts', to='accounts.employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_receipts', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'import_receipt',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('sale_price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.employee')),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='ImportReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('import_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='warehouse.importreceipt')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_receipt_details', to='warehouse.medicine')),
            ],
            options={
                'db_table': 'import_receipt_detail',
                'unique_together': {('import_receipt', 'medicine')},
            },
        ),
        migrations.CreateModel(
            name='ExportReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('insurance_covered', models.BooleanField(default=True)),
                ('ins_amount', models.FloatField(default=0)),
                ('patient_pay', models.FloatField(default=0)),
                ('export_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='warehouse.exportreceipt')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_receipt_details', to='warehouse.medicine')),
            ],
            options={
                'db_table': 'export_receipt_detail',
                'unique_together': {('export_receipt', 'medicine')},
            },
        ),
    ]
