# Generated by Django 5.0.9 on 2025-01-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportreceiptdetail',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
