# Generated by Django 5.1.3 on 2025-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="employee",
        ),
        migrations.AddField(
            model_name="exportreceipt",
            name="is_approved",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="importreceipt",
            name="is_approved",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(default=1),
        ),
    ]
