# Generated by Django 5.1.3 on 2025-01-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0002_remove_medicine_employee_exportreceipt_is_approved_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreceipt",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="exportreceiptdetail",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="importreceipt",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="importreceiptdetail",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
