# Generated by Django 5.1.3 on 2025-01-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_exportreceipt_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportreceipt",
            name="export_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="importreceipt",
            name="import_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="unit",
            field=models.CharField(default="Viên", max_length=50),
        ),
    ]
