# Generated by Django 5.1.3 on 2024-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instruction',
            field=models.CharField(default='', max_length=300),
        ),
    ]
