# Generated by Django 5.1.3 on 2024-12-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_patient_insurance_alter_prescription_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nguoi_giam_ho',
            field=models.CharField(default='Không có', max_length=50),
        ),
    ]
