# Generated by Django 5.1.3 on 2025-01-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0004_patient_nguoi_giam_ho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="nguoi_giam_ho",
        ),
    ]
