# Generated by Django 5.1.3 on 2025-01-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_employee_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
