# Generated by Django 5.1.3 on 2025-01-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_employee_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
