# Generated by Django 5.1.3 on 2025-01-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_employee_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_images/"
            ),
        ),
    ]
