# Generated by Django 5.1.3 on 2025-01-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_employee_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="citizen_id",
            field=models.CharField(default="", max_length=13),
        ),
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                default="employee_images/default.png", upload_to="employee_images/"
            ),
        ),
    ]
