# Generated by Django 5.1.3 on 2025-01-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_employee_citizen_id_alter_employee_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="citizen_id",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
